version: 2.1

orbs:
  lambda-ingestor: evgenoid/aws-lambda-ingestor@1.1.0

workflows:
  version: 2.1
  hello:
    jobs:
      - lambda-ingestor/build
      - lambda-ingestor/deploy:
          requires:
            - lambda-ingestor/build

